server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        webAllowOthers: true
  jpa:
    showSql: true
    ddlAuto: create
  sql:
    init:
      encoding: UTF-8